# Generated by Django 3.0.6 on 2020-06-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('beds', models.PositiveIntegerField(default=0, null=True)),
                ('baths', models.PositiveIntegerField(default=0, null=True)),
                ('floors', models.PositiveIntegerField(default=1, null=True)),
                ('metro', models.CharField(max_length=50, null=True)),
                ('area', models.FloatField(default=0, null=True)),
                ('size', models.FloatField(default=0, null=True)),
                ('photoURL', models.URLField(null=True)),
                ('videoURL', models.URLField(null=True)),
                ('photo', models.FileField(upload_to='upload/')),
                ('address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Type')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
