# Generated by Django 3.0.6 on 2020-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200603_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
